title: My GitHub Pages Site
description: A simple site using GitHub Pages and Jekyll
baseurl: "" # If not using a subfolder
url: "https://2024acheong.github.io" # Replace with your GitHub Pages URL
theme: jekyll-theme-primer # Or another theme you want to use
exclude:
  - backend/venv
